# -*- coding: utf-8 -*-
"""semantic_passport_v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oKfGZKdly0QUFCG4bLng77zHoL5CdNWx
"""

import hashlib
import hmac
import time
import json

class SemanticPassport:
    """에이전트의 신원 및 의도를 고착화(Anchoring)하는 증명 모듈"""

    def __init__(self, agent_id, secret_key):
        self.agent_id = agent_id
        self.secret_key = secret_key

    def generate_ticket(self, intent_context):
        """
        의도(Intent)와 시각(Timestamp)을 결합하여 가변적 패스포트 생성
        단순 API Key가 아닌, 매 호출마다 변하는 '행동 지문' 생성
        """
        timestamp = str(int(time.time() // 30)) # 30초 단위 갱신
        # 의도(Context)를 해시화하여 신원에 고착(Identity Anchoring)
        payload = f"{self.agent_id}:{intent_context}:{timestamp}"
        signature = hmac.new(
            self.secret_key.encode(),
            payload.encode(),
            hashlib.sha256
        ).hexdigest()

        return {
            "passport_id": f"SP-{self.agent_id}",
            "intent_anchor": signature,
            "issued_at": timestamp
        }

class ZeroTrustA2A:
    """Zero-Trust 기반 에이전트 간 상호 검증 프로토콜"""

    def __init__(self):
        self.trust_registry = {} # 승인된 에이전트 관리

    def register_agent(self, agent_id, secret_key):
        self.trust_registry[agent_id] = secret_key

    def verify_intent(self, passport, intent_context):
        """행동 기반 인증(Behavioral Auth) 및 의도 검증"""
        agent_id = passport['passport_id'].replace("SP-", "")
        secret_key = self.trust_registry.get(agent_id)

        if not secret_key:
            return False, "❌ Unknown Agent: 신원 미확인"

        # 수신된 의도와 타임스탬프로 서명 재현 (Verification)
        expected_payload = f"{agent_id}:{intent_context}:{passport['issued_at']}"
        expected_signature = hmac.new(
            secret_key.encode(),
            expected_payload.encode(),
            hashlib.sha256
        ).hexdigest()

        if hmac.compare_digest(expected_signature, passport['intent_anchor']):
            return True, "✅ Verified: 의도와 신원이 일치하는 정당한 에이전트"
        else:
            return False, "⚠️ Alert: 신원은 일치하나 의도가 변조되었거나 시간이 초과됨"

# --- 실전 증명 시뮬레이션 ---
lab_gate = ZeroTrustA2A()
lab_gate.register_agent("TOBECON_BOT", "MULBERRY_SECRET_SHARED")

# 1. TOBECON 에이전트가 '주문 데이터 조회' 의도를 가지고 접근
agent_tob = SemanticPassport("TOBECON_BOT", "MULBERRY_SECRET_SHARED")
intent = "GET_ORDER_DATA_V1"
passport_ticket = agent_tob.generate_ticket(intent)

print(f"📡 [A2A 요청] Passport 생성 완료: {passport_ticket['passport_id']}")

# 2. Lab Gate에서 검증 (Zero-Trust)
is_valid, message = lab_gate.verify_intent(passport_ticket, intent)
print(f"🛡️ [검증 결과] {message}")

# 3. 만약 해커가 Passport를 탈취해 다른 의도(DELETE_ALL)로 접근한다면?
is_valid_hack, msg_hack = lab_gate.verify_intent(passport_ticket, "DELETE_DATABASE")
print(f"🚨 [변조 공격 대응] {msg_hack}")



"""[이 소스코드가 증명하는 가치]
Identity Anchoring: 단순히 "키가 맞는가?"를 묻지 않고, "이 키를 가진 자가 원래의 목적(Intent)대로 움직이는가?"를 검증합니다.

Behavioral Auth: 30초 단위로 변하는 타임스탬프와 의도 텍스트를 결합하여, 한 번 탈취된 패스포트가 재사용되는 것을 방지합니다.

Zero-Trust: 에이전트 내부라 할지라도 모든 통신은 매 순간 신원을 증명해야 한다는 원칙을 코드로 구현했습니다.

### 여러 에이전트 등록 및 관리 예제

이제 `ZeroTrustA2A` 클래스를 사용하여 여러 에이전트를 등록하고, 각 에이전트가 다른 의도(intent)로 시스템에 접근할 때 상호 검증하는 시나리오를 시뮬레이션해 보겠습니다.
"""

import hashlib
import hmac
import time
import json

class SemanticPassport:
    """에이전트의 신원 및 의도를 고착화(Anchoring)하는 증명 모듈"""

    def __init__(self, agent_id, secret_key):
        self.agent_id = agent_id
        self.secret_key = secret_key

    def generate_ticket(self, intent_context):
        """
        의도(Intent)와 시각(Timestamp)을 결합하여 가변적 패스포트 생성
        단순 API Key가 아닌, 매 호출마다 변하는 '행동 지문' 생성
        """
        timestamp = str(int(time.time() // 30)) # 30초 단위 갱신
        # 의도(Context)를 해시화하여 신원에 고착(Identity Anchoring)
        payload = f"{self.agent_id}:{intent_context}:{timestamp}"
        signature = hmac.new(
            self.secret_key.encode(),
            payload.encode(),
            hashlib.sha256
        ).hexdigest()

        return {
            "passport_id": f"SP-{self.agent_id}",
            "intent_anchor": signature,
            "issued_at": timestamp
        }

class ZeroTrustA2A:
    """Zero-Trust 기반 에이전트 간 상호 검증 프로토콜"""

    def __init__(self):
        self.trust_registry = {} # 승인된 에이전트 관리
        self.security_logs = []  # 보안 로그를 저장할 리스트 추가

    def register_agent(self, agent_id, secret_key):
        self.trust_registry[agent_id] = secret_key
        self.security_logs.append({
            "timestamp": time.time(),
            "event": "Agent Registered",
            "agent_id": agent_id
        })

    def notify_agents(self, source_agent_id, alert_message):
        """ 다른 에이전트들에게 보안 알림을 전파하는 시뮬레이션 """
        log_entry = {
            "timestamp": time.time(),
            "event": "Security Alert",
            "source_agent": source_agent_id,
            "message": alert_message
        }
        self.security_logs.append(log_entry)
        print(f"📢 [보안 알림] 발신 에이전트: {source_agent_id}, 메시지: {alert_message}")
        # 실제 구현에서는 여기에 메시지 큐, API 호출 등의 로직 추가

    def report_security_incident(self, incident_type, agent_id, attempted_intent=None, message=None):
        """ 보안 사고 발생 시 보고서를 생성하고 기록합니다. """
        incident_report = {
            "timestamp": time.time(),
            "event": "Security Incident Report",
            "incident_type": incident_type,
            "agent_id": agent_id,
            "attempted_intent": attempted_intent if attempted_intent else "N/A",
            "message": message if message else f"[{incident_type}] 에이전트 {agent_id} 관련 사고 발생"
        }
        self.security_logs.append(incident_report)
        # 보안 알림과 별개로 사고 보고를 처리할 수 있습니다.
        # 예를 들어, SIEM 시스템에 전송하거나 별도의 보고서 파일을 생성할 수 있습니다.
        print(f"❗️ [사고 보고] {incident_report['message']}")

    def verify_intent(self, passport, intent_context):
        """행동 기반 인증(Behavioral Auth) 및 의도 검증"""
        agent_id = passport['passport_id'].replace("SP-", "")
        secret_key = self.trust_registry.get(agent_id)

        log_entry = {
            "timestamp": time.time(),
            "event": "Intent Verification Attempt",
            "agent_id": agent_id,
            "attempted_intent": intent_context,
            "passport_issued_at": passport['issued_at']
        }

        if not secret_key:
            alert_message = f"미등록 에이전트({agent_id})의 접근 시도: {intent_context}"
            self.notify_agents("SYSTEM_GATEWAY", alert_message)
            self.report_security_incident(
                incident_type="Unknown Agent Access Attempt",
                agent_id=agent_id,
                attempted_intent=intent_context,
                message=f"미등록 에이전트 {agent_id}가 의도 {intent_context}로 접근 시도."
            )
            log_entry["status"] = "Failed - Unknown Agent"
            log_entry["result_message"] = "❌ Unknown Agent: 신원 미확인"
            self.security_logs.append(log_entry)
            return False, "❌ Unknown Agent: 신원 미확인"

        # 수신된 의도와 타임스탬프로 서명 재현 (Verification)
        expected_payload = f"{agent_id}:{intent_context}:{passport['issued_at']}"
        expected_signature = hmac.new(
            secret_key.encode(),
            expected_payload.encode(),
            hashlib.sha256
        ).hexdigest()

        if hmac.compare_digest(expected_signature, passport['intent_anchor']):
            log_entry["status"] = "Success"
            log_entry["result_message"] = "✅ Verified: 의도와 신원이 일치하는 정당한 에이전트"
            self.security_logs.append(log_entry)
            return True, "✅ Verified: 의도와 신원이 일치하는 정당한 에이전트"
        else:
            alert_message = f"에이전트({agent_id})의 의도 변조 시도! (원래 의도: N/A, 시도 의도: {intent_context})" # 'original_intent'는 passport에 없으므로 N/A로 표시
            self.notify_agents(agent_id, alert_message)
            self.report_security_incident(
                incident_type="Intent Tampering Attempt",
                agent_id=agent_id,
                attempted_intent=intent_context,
                message=f"에이전트 {agent_id}가 의도 {intent_context}로 변조된 접근 시도."
            )
            log_entry["status"] = "Failed - Intent Tampered or Expired"
            log_entry["result_message"] = "⚠️ Alert: 신원은 일치하나 의도가 변조되었거나 시간이 초과됨"
            self.security_logs.append(log_entry)
            return False, "⚠️ Alert: 신원은 일치하나 의도가 변조되었거나 시간이 초과됨"

    def get_security_logs(self):
        """ 기록된 모든 보안 로그를 반환합니다. """
        return self.security_logs

"""### 보안 에이전트 오피스: 신원 미확인/의도 변조 에이전트 신고 시뮬레이션

업데이트된 `ZeroTrustA2A` 클래스는 이제 `report_security_incident` 메서드를 통해 보안 사고를 기록합니다. 다음 시뮬레이션은 미등록 에이전트의 접근 시도와 의도 변조 시도를 통해 이러한 보고서가 어떻게 생성되는지 보여줍니다.
"""

# 새로운 ZeroTrustA2A 게이트웨이 초기화
security_office_gate = ZeroTrustA2A()

# 1. 등록된 에이전트
security_office_gate.register_agent("DATA_ANALYST_BOT", "SECRET_ANALYST")
security_office_gate.register_agent("INFRA_MAINT_BOT", "SECRET_INFRA")

print("--- 에이전트 등록 완료 ---")
print(f"등록된 에이전트: {list(security_office_gate.trust_registry.keys())}\n")

# 2. DATA_ANALYST_BOT의 정상적인 '데이터 조회' 의도
analyst_agent = SemanticPassport("DATA_ANALYST_BOT", "SECRET_ANALYST")
analyst_intent = "QUERY_SALES_DATA_Q3"
analyst_passport = analyst_agent.generate_ticket(analyst_intent)

print(f"📡 [DATA_ANALYST_BOT 요청] Passport 생성 완료: {analyst_passport['passport_id']}")
is_valid_analyst, msg_analyst = security_office_gate.verify_intent(analyst_passport, analyst_intent)
print(f"🛡️ [DATA_ANALYST_BOT 검증 결과] {msg_analyst}\n")

# 3. 신원 미확인(Unregistered) 에이전트의 접근 시도 (자동으로 사고 보고 발생)
unknown_agent = SemanticPassport("FOREIGN_ENTITY_BOT", "UNKNOWN_SECRET")
unknown_intent = "ATTEMPT_ACCESS_ALL_DB"
unknown_passport = unknown_agent.generate_ticket(unknown_intent)

print(f"📡 [FOREIGN_ENTITY_BOT 요청] Passport 생성 완료: {unknown_passport['passport_id']}")
is_valid_unknown, msg_unknown = security_office_gate.verify_intent(unknown_passport, unknown_intent)
print(f"🚨 [FOREIGN_ENTITY_BOT 검증 결과] {msg_unknown}\n")

# 4. INFRA_MAINT_BOT이 '데이터 삭제' 의도로 변조된 접근 시도 (의도 변조 감지 및 사고 보고)
infra_agent = SemanticPassport("INFRA_MAINT_BOT", "SECRET_INFRA")
infra_intent = "MAINTAIN_SERVER_HEALTH"
infra_passport = infra_agent.generate_ticket(infra_intent)

# 의도를 'DELETE_ALL_DATA'로 변조 시도
infr_tampered_intent = "DELETE_ALL_DATA"
is_valid_tampered, msg_tampered = security_office_gate.verify_intent(infra_passport, infr_tampered_intent)
print(f"🚨 [INFRA_MAINT_BOT 의도 변조 대응] {msg_tampered}\n")

# 5. 시간 초과된 패스포트 시도 (시간 경과를 시뮬레이션하기 위해 새 타임스탬프 사용)
# 실제 시간 경과를 위해 30초 대기 또는 다른 타임스탬프 강제 적용 필요
# 여기서는 간단히 새로운 티켓을 생성하되, 이전 의도와 다른 타임스탬프를 가진 것처럼 시뮬레이션
# (실제 환경에서는 30초 이상 대기해야 함)
# for simplicity, let's just make another call with the same intent after a 'simulated' time lapse
# (in a real scenario, the timestamp check would fail due to actual time passing)
# For demonstration, we will rely on the `intent_tampered_or_expired` logic
# A more direct way to simulate expiration would be to manually alter the 'issued_at' field of a valid passport ticket.

# INFRA_MAINT_BOT의 유효한 패스포트를 다시 생성하여, 이후에 '만료된' 시나리오를 위한 기반 마련
infr_valid_passport_for_expiry_test = infra_agent.generate_ticket(infra_intent)

# 의도적으로 이전 issued_at을 사용하되, 현재 시간 기준으로는 만료된 것으로 간주
expired_passport = infr_valid_passport_for_expiry_test.copy()
expired_passport['issued_at'] = str(int(time.time() // 30) - 2) # 1분 이상 지난 것으로 시뮬레이션

print(f"📡 [INFRA_MAINT_BOT 요청] 만료된 Passport 시뮬레이션: {expired_passport['passport_id']}")
is_valid_expired, msg_expired = security_office_gate.verify_intent(expired_passport, infra_intent)
print(f"🚨 [INFRA_MAINT_BOT 만료된 Passport 대응] {msg_expired}\n")

"""### 생성된 보안 사고 보고서 확인

이제 `security_office_gate`에 기록된 모든 보안 로그를 확인하여, 앞에서 발생시킨 사고 보고서들을 살펴볼 수 있습니다.
"""

print("--- 전체 보안 로그 및 사고 보고서 ---")
all_security_office_logs = security_office_gate.get_security_logs()
for log_entry in all_security_office_logs:
    print(json.dumps(log_entry, indent=2, ensure_ascii=False))

"""### 특정 유형의 보안 사고 보고서 필터링

생성된 로그 중에서 'Security Incident Report'만 필터링하여 확인해 보겠습니다.
"""

print("--- 'Security Incident Report'만 필터링 ---")
incident_reports = [log for log in security_office_gate.get_security_logs() if log['event'] == 'Security Incident Report']

if incident_reports:
    for report in incident_reports:
        print(json.dumps(report, indent=2, ensure_ascii=False))
else:
    print("기록된 'Security Incident Report'가 없습니다.")

"""### 여러 에이전트 등록 및 관리 예제

이제 `ZeroTrustA2A` 클래스를 사용하여 여러 에이전트를 등록하고, 각 에이전트가 다른 의도(intent)로 시스템에 접근할 때 상호 검증하는 시나리오를 시뮬레이션해 보겠습니다.
"""

# 새로운 ZeroTrustA2A 게이트웨이 초기화 (기존 시뮬레이션과 별개로)
multi_agent_gate = ZeroTrustA2A()

# 1. 여러 에이전트 등록
multi_agent_gate.register_agent("HR_BOT", "SECRET_KEY_HR")
multi_agent_gate.register_agent("FINANCE_BOT", "SECRET_KEY_FINANCE")
multi_agent_gate.register_agent("LOGISTICS_BOT", "SECRET_KEY_LOGISTICS")

print("--- 여러 에이전트 등록 완료 ---")
print(f"등록된 에이전트: {list(multi_agent_gate.trust_registry.keys())}\n")

# 2. HR BOT의 '직원 정보 조회' 의도 검증
agent_hr = SemanticPassport("HR_BOT", "SECRET_KEY_HR")
hr_intent = "GET_EMPLOYEE_DATA"
hr_passport = agent_hr.generate_ticket(hr_intent)

print(f"📡 [HR BOT 요청] Passport 생성 완료: {hr_passport['passport_id']}")
is_valid_hr, msg_hr = multi_agent_gate.verify_intent(hr_passport, hr_intent)
print(f"🛡️ [HR BOT 검증 결과] {msg_hr}\n")

# 3. FINANCE BOT의 '급여 보고서 생성' 의도 검증
agent_finance = SemanticPassport("FINANCE_BOT", "SECRET_KEY_FINANCE")
finance_intent = "GENERATE_PAYROLL_REPORT"
finance_passport = agent_finance.generate_ticket(finance_intent)

print(f"📡 [FINANCE BOT 요청] Passport 생성 완료: {finance_passport['passport_id']}")
is_valid_finance, msg_finance = multi_agent_gate.verify_intent(finance_passport, finance_intent)
print(f"🛡️ [FINANCE BOT 검증 결과] {msg_finance}\n")

# 4. LOGISTICS BOT의 '재고 현황 업데이트' 의도 검증
agent_logistics = SemanticPassport("LOGISTICS_BOT", "SECRET_KEY_LOGISTICS")
logistics_intent = "UPDATE_INVENTORY_STATUS"
logistics_passport = agent_logistics.generate_ticket(logistics_intent)

print(f"📡 [LOGISTICS BOT 요청] Passport 생성 완료: {logistics_passport['passport_id']}")
is_valid_logistics, msg_logistics = multi_agent_gate.verify_intent(logistics_passport, logistics_intent)
print(f"🛡️ [LOGISTICS BOT 검증 결과] {msg_logistics}\n")

# 5. 미등록 에이전트의 접근 시도
unregistered_agent = SemanticPassport("ROGUE_BOT", "UNKNOWN_SECRET")
rogue_intent = "ACCESS_ALL_DATA"
rogue_passport = unregistered_agent.generate_ticket(rogue_intent)

print(f"📡 [ROGUE BOT 요청] Passport 생성 완료: {rogue_passport['passport_id']}")
is_valid_rogue, msg_rogue = multi_agent_gate.verify_intent(rogue_passport, rogue_intent)
print(f"🚨 [ROGUE BOT 검증 결과] {msg_rogue}\n")

# 6. HR BOT이 '급여 보고서 생성' 의도로 변조된 접근 시도 (의도 변조)
hr_modified_intent = "GENERATE_PAYROLL_REPORT" # HR BOT이 FINANCE BOT의 의도를 흉내
is_valid_hr_mod, msg_hr_mod = multi_agent_gate.verify_intent(hr_passport, hr_modified_intent)
print(f"🚨 [HR BOT 의도 변조 대응] {msg_hr_mod}\n")

"""### 저장된 보안 로그 확인

이제 `multi_agent_gate`에 기록된 모든 보안 로그를 확인해 보겠습니다.
"""

print("--- 전체 보안 로그 ---")
for log_entry in multi_agent_gate.get_security_logs():
    print(json.dumps(log_entry, indent=2, ensure_ascii=False))

"""### 특정 에이전트의 로그 필터링"""

# 필터링할 에이전트 ID를 지정하세요.
target_agent_id = "HR_BOT" # 예시: "HR_BOT", "FINANCE_BOT", "ROGUE_BOT"

print(f"--- '{target_agent_id}' 에이전트의 보안 로그 ---")
filtered_logs = []
for log_entry in multi_agent_gate.get_security_logs():
    # 'agent_id' 필드가 있거나, 'source_agent' 필드가 target_agent_id와 일치하는 경우를 필터링
    if (log_entry.get('agent_id') == target_agent_id) or \
       (log_entry.get('source_agent') == target_agent_id):
        filtered_logs.append(log_entry)

if filtered_logs:
    for log in filtered_logs:
        print(json.dumps(log, indent=2, ensure_ascii=False))
else:
    print(f"'{target_agent_id}' 에이전트에 대한 로그가 없습니다.")

"""### 보안 로그를 Pandas DataFrame으로 변환 및 시각화 준비"""

import pandas as pd

# multi_agent_gate에서 보안 로그 가져오기
all_security_logs = multi_agent_gate.get_security_logs()

# 로그를 Pandas DataFrame으로 변환
security_df = pd.DataFrame(all_security_logs)

# 'timestamp' 컬럼을 datetime 객체로 변환하여 시간 기반 분석을 용이하게 합니다.
security_df['timestamp'] = pd.to_datetime(security_df['timestamp'], unit='s')

print("--- 변환된 보안 로그 데이터프레임 ---\n")
display(security_df.head())
print("\n--- 데이터프레임 정보 ---")
security_df.info()

"""### 에이전트별 보안 이벤트 발생 횟수 집계"""

# 'agent_id'와 'source_agent' 컬럼을 통합하여 실제 이벤트 주체를 명확히 합니다.
# 'event'가 'Security Alert'일 경우 'source_agent'를 우선 사용하고, 그 외에는 'agent_id'를 사용합니다.
# 이렇게 하면 SYSTEM_GATEWAY에서 발생한 알림도 집계에 포함됩니다.

# 'actual_agent' 컬럼 생성
def get_actual_agent(row):
    if row['event'] == 'Security Alert' and pd.notna(row['source_agent']):
        return row['source_agent']
    elif pd.notna(row['agent_id']):
        return row['agent_id']
    return 'UNKNOWN'

security_df['actual_agent'] = security_df.apply(get_actual_agent, axis=1)

# 'actual_agent' 및 'event' 타입별로 집계
agent_event_counts = security_df.groupby(['actual_agent', 'event']).size().reset_index(name='count')

print("--- 에이전트별 보안 이벤트 발생 횟수 ---\n")
display(agent_event_counts)

"""### 에이전트별 보안 이벤트 시각화"""

import matplotlib.pyplot as plt
import seaborn as sns

# 그래프 크기 설정
plt.figure(figsize=(12, 6))

# 막대 그래프 생성
sns.barplot(x='actual_agent', y='count', hue='event', data=agent_event_counts)

# 그래프 제목 및 라벨 설정
plt.title('Agent-wise Security Event Counts')
plt.xlabel('Agent ID')
plt.ylabel('Event Count')
plt.xticks(rotation=45, ha='right') # x축 라벨 회전
plt.legend(title='Event Type', bbox_to_anchor=(1.05, 1), loc='upper left') # 범례 위치 조정
plt.tight_layout() # 레이아웃 자동 조정

# 그래프 표시
plt.show()

# 새로운 ZeroTrustA2A 게이트웨이 초기화 (기존 시뮬레이션과 별개로)
multi_agent_gate = ZeroTrustA2A()

# 1. 여러 에이전트 등록
multi_agent_gate.register_agent("HR_BOT", "SECRET_KEY_HR")
multi_agent_gate.register_agent("FINANCE_BOT", "SECRET_KEY_FINANCE")
multi_agent_gate.register_agent("LOGISTICS_BOT", "SECRET_KEY_LOGISTICS")

print("--- 여러 에이전트 등록 완료 ---")
print(f"등록된 에이전트: {list(multi_agent_gate.trust_registry.keys())}\n")

# 2. HR BOT의 '직원 정보 조회' 의도 검증
agent_hr = SemanticPassport("HR_BOT", "SECRET_KEY_HR")
hr_intent = "GET_EMPLOYEE_DATA"
hr_passport = agent_hr.generate_ticket(hr_intent)

print(f"📡 [HR BOT 요청] Passport 생성 완료: {hr_passport['passport_id']}")
is_valid_hr, msg_hr = multi_agent_gate.verify_intent(hr_passport, hr_intent)
print(f"🛡️ [HR BOT 검증 결과] {msg_hr}\n")

# 3. FINANCE BOT의 '급여 보고서 생성' 의도 검증
agent_finance = SemanticPassport("FINANCE_BOT", "SECRET_KEY_FINANCE")
finance_intent = "GENERATE_PAYROLL_REPORT"
finance_passport = agent_finance.generate_ticket(finance_intent)

print(f"📡 [FINANCE BOT 요청] Passport 생성 완료: {finance_passport['passport_id']}")
is_valid_finance, msg_finance = multi_agent_gate.verify_intent(finance_passport, finance_intent)
print(f"🛡️ [FINANCE BOT 검증 결과] {msg_finance}\n")

# 4. LOGISTICS BOT의 '재고 현황 업데이트' 의도 검증
agent_logistics = SemanticPassport("LOGISTICS_BOT", "SECRET_KEY_LOGISTICS")
logistics_intent = "UPDATE_INVENTORY_STATUS"
logistics_passport = agent_logistics.generate_ticket(logistics_intent)

print(f"📡 [LOGISTICS BOT 요청] Passport 생성 완료: {logistics_passport['passport_id']}")
is_valid_logistics, msg_logistics = multi_agent_gate.verify_intent(logistics_passport, logistics_intent)
print(f"🛡️ [LOGISTICS BOT 검증 결과] {msg_logistics}\n")

# 5. 미등록 에이전트의 접근 시도
unregistered_agent = SemanticPassport("ROGUE_BOT", "UNKNOWN_SECRET")
rogue_intent = "ACCESS_ALL_DATA"
rogue_passport = unregistered_agent.generate_ticket(rogue_intent)

print(f"📡 [ROGUE BOT 요청] Passport 생성 완료: {rogue_passport['passport_id']}")
is_valid_rogue, msg_rogue = multi_agent_gate.verify_intent(rogue_passport, rogue_intent)
print(f"🚨 [ROGUE BOT 검증 결과] {msg_rogue}\n")

# 6. HR BOT이 '급여 보고서 생성' 의도로 변조된 접근 시도 (의도 변조)
hr_modified_intent = "GENERATE_PAYROLL_REPORT" # HR BOT이 FINANCE BOT의 의도를 흉내
is_valid_hr_mod, msg_hr_mod = multi_agent_gate.verify_intent(hr_passport, hr_modified_intent)
print(f"🚨 [HR BOT 의도 변조 대응] {msg_hr_mod}\n")

"""### 저장된 보안 로그 확인

이제 `multi_agent_gate`에 기록된 모든 보안 로그를 확인해 보겠습니다.
"""

print("--- 전체 보안 로그 ---")
for log_entry in multi_agent_gate.get_security_logs():
    print(json.dumps(log_entry, indent=2, ensure_ascii=False))

"""### 특정 에이전트의 로그 필터링"""

# 필터링할 에이전트 ID를 지정하세요.
target_agent_id = "HR_BOT" # 예시: "HR_BOT", "FINANCE_BOT", "ROGUE_BOT"

print(f"--- '{target_agent_id}' 에이전트의 보안 로그 ---")
filtered_logs = []
for log_entry in multi_agent_gate.get_security_logs():
    # 'agent_id' 필드가 있거나, 'source_agent' 필드가 target_agent_id와 일치하는 경우를 필터링
    if (log_entry.get('agent_id') == target_agent_id) or \
       (log_entry.get('source_agent') == target_agent_id):
        filtered_logs.append(log_entry)

if filtered_logs:
    for log in filtered_logs:
        print(json.dumps(log, indent=2, ensure_ascii=False))
else:
    print(f"'{target_agent_id}' 에이전트에 대한 로그가 없습니다.")

"""### 보안 로그를 Pandas DataFrame으로 변환 및 시각화 준비"""

import pandas as pd

# multi_agent_gate에서 보안 로그 가져오기
all_security_logs = multi_agent_gate.get_security_logs()

# 로그를 Pandas DataFrame으로 변환
security_df = pd.DataFrame(all_security_logs)

# 'timestamp' 컬럼을 datetime 객체로 변환하여 시간 기반 분석을 용이하게 합니다.
security_df['timestamp'] = pd.to_datetime(security_df['timestamp'], unit='s')

print("--- 변환된 보안 로그 데이터프레임 ---\n")
display(security_df.head())
print("\n--- 데이터프레임 정보 ---")
security_df.info()

"""### 에이전트별 보안 이벤트 발생 횟수 집계"""

# 'agent_id'와 'source_agent' 컬럼을 통합하여 실제 이벤트 주체를 명확히 합니다.
# 'event'가 'Security Alert'일 경우 'source_agent'를 우선 사용하고, 그 외에는 'agent_id'를 사용합니다.
# 이렇게 하면 SYSTEM_GATEWAY에서 발생한 알림도 집계에 포함됩니다.

# 'actual_agent' 컬럼 생성
def get_actual_agent(row):
    if row['event'] == 'Security Alert' and pd.notna(row['source_agent']):
        return row['source_agent']
    elif pd.notna(row['agent_id']):
        return row['agent_id']
    return 'UNKNOWN'

security_df['actual_agent'] = security_df.apply(get_actual_agent, axis=1)

# 'actual_agent' 및 'event' 타입별로 집계
agent_event_counts = security_df.groupby(['actual_agent', 'event']).size().reset_index(name='count')

print("--- 에이전트별 보안 이벤트 발생 횟수 ---\n")
display(agent_event_counts)

"""### 에이전트별 보안 이벤트 시각화"""

import matplotlib.pyplot as plt
import seaborn as sns

# 그래프 크기 설정
plt.figure(figsize=(12, 6))

# 막대 그래프 생성
sns.barplot(x='actual_agent', y='count', hue='event', data=agent_event_counts)

# 그래프 제목 및 라벨 설정
plt.title('Agent-wise Security Event Counts')
plt.xlabel('Agent ID')
plt.ylabel('Event Count')
plt.xticks(rotation=45, ha='right') # x축 라벨 회전
plt.legend(title='Event Type', bbox_to_anchor=(1.05, 1), loc='upper left') # 범례 위치 조정
plt.tight_layout() # 레이아웃 자동 조정

# 그래프 표시
plt.show()